name: Release

on:
  push:
    branches: ['release/*']

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GH_NEW_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build subapp
        run: |
          $root = $env:GITHUB_WORKSPACE
          git clone https://github.com/lisiqingKING/internal-app.git "$root\apps\app-temp"
          cd "$root\apps\app-temp"
          npm ci
          npm run build
          robocopy "$root\apps\app-temp\dist" "$root\apps\internal-app\dist" /E
          cd $root
          Remove-Item -Recurse -Force "$root\apps\app-temp"
          exit 0

      - name: Build
        run: npm run build

      - name: Build and publish Electron
        run: npx electron-builder --publish always -w
