name: Release

on:
  push:
    branches: ['release/*']

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build and publish Electron
        run: npx electron-builder --publish always -w
        env:
          GH_TOKEN: ${{ secrets.GH_NEW_TOKEN }}
